# Generated by Django 4.0.5 on 2022-06-09 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
